### ISSUE TITLE
Set up TravisCI

### ISSUE THREAD

**Issue by slifty** [qco/bookliberator#13]
## Task
**Description**
I will feel much more comfortable if we use TravisCI compile builds and run tests on PRs.  This is particularly valuable because we don't have full code reviews on the project at this stage.

CI should:

* [ ] run the linter
* [ ] run the tests
* [ ] build the project

**Relevant resources / research**
* [TravisCI: Building an Android Project](https://docs.travis-ci.com/user/languages/android/)

**Related Issues**
This is part of issue #4

**Comment by slifty** [comment]
@kfogel Would you be willing to add TravisCI to this project?  The first three steps of [this guide](https://docs.travis-ci.com/user/tutorial/) will do the trick.

I should note, Travis is not FOSS but it is "Free" for open source projects.  Using Travis instead of a FOSS alternative like Jenkins is a matter of convenience / fitting our budget right now.  We are NOT locked into travis by using it now / it won't make it harder to use Jenkins later, and it does not affect the ability to develop.

**Comment by kfogel** [comment]
Thanks for asking, @slifty.  Travis is okay for now, since no developer will have to run it on their own machine, but of course it's not ideal.  Could you please make a note of it in an issue as a proprietary semi-dependency that we'd like to get rid of soon?  (And if I found someone to make the equivalent setup w/ Jenkins, presumably having them do the switchover wouldn't impose any time costs on you, right?)

**Comment by slifty** [comment]
Excellent thank you -- FWIW I do see travis as similar to github in that the project doesn't need it to function or continue, it is just providing utility *for now* that could be replaced later with a FOSS solution.

And correct, no time cost on my end to switch later!  Using travis now should be a matter of minutes to set up.
